### ISSUE TITLE
couldn't find "libimageutils.so"

### ISSUE THREAD

**Issue by androidroadies** [Catchoom/craftar-example-android-image-recognition#7]
FATAL EXCEPTION: main
                                                                 Process: com.catchoom.test, PID: 1234
                                                                 java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.catchoom.test-1/base.apk", zip file "/data/app/com.catchoom.test-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.catchoom.test-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.catchoom.test-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.catchoom.test-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.catchoom.test-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.catchoom.test-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.catchoom.test-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.catchoom.test-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.catchoom.test-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.catchoom.test-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.catchoom.test-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.catchoom.test-1/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libimageutils.so"
                                                                     at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                     at java.lang.System.loadLibrary(System.java:1076)
                                                                     at com.craftar.UtilsImage.<clinit>(UtilsImage.java:35)
                                                                     at com.craftar.UtilsImage.Instance(UtilsImage.java:72)
                                                                     at com.craftar.CraftARActivity.onCreate(CraftARActivity.java:37)
                                                                     at android.app.Activity.performCreate(Activity.java:6259)
                                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
                                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
                                                                     at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by martinell** [comment]
What device and android version are you testing it on?

**Comment by androidroadies** [comment]
Device Moto G
OS: 6.0.1

**Comment by Quelake** [comment]
Any resolution to this bug? I am experiencing the same thing, running Pixel 3a emulator on Android Studio Arctic Fox | 2020.3.1 Patch 4
